version: '3.6'
services:
  tizen:
    image: tizenstudio:webcli-5.0-test
    container_name: tizen
    volumes:
      - ./code:/code
      - ./demo:/code/demo
    restart: unless-stopped
    networks:
      - tizen

networks:
  tizen:
    name: tizen-net
  